
;new
		{"bullet35 zenite" "AP 35mm Zenite"}
		{"bullet30 zenite" "AP 30mm Zenite"}
		{"bullet23 zenite" "AP 23mm Zenite"}
		{"bullet105 ap-new" "APFSDS 105mm"}
		{"bullet100 ap-new" "APFSDS 100mm"}
		{"bullet121 ap" "APFSDS 120mm"}
		{"bullet121 fg" "HE 120mm"}
		{"bullet121 heat" "HEAT 120mm"}
		{"bullet125 ap-type99" "APFSDS 125mm"}
		{"bullet125 fg-type99" "HE 125mm"}
		{"bullet125 heat-type99" "HEAT 125mm"}
		{"bullet125 ap" "APFSDS 125mm"}
		{"bullet125 fg" "HE 125mm"}
		{"bullet125 heat" "HEAT 125mm"}
		{"bullet183 ap" "AP 183mm"}
		{"bullet183 apcr" "APCR 183mm"}
		{"bullet183 fg" "HE 183mm"}
		{"bullet170 ap" "AP 170mm"}
		{"bullet170 apcr" "APCR 170mm"}
		{"bullet170 fg" "HE 170mm"}
		{"bullet155 ap" "AP 155mm"}
		{"bullet130 ap" "AP 130mm"}
		{"bullet130 apcr" "APCR 130mm"}
		{"bullet130 fg" "HE 130mm"}
		{"bullet115 ap" "AP 115mm"}
		{"bullet115 apcr" "APCR 115mm"}
		{"bullet115 fg" "HE 115mm"}
		{"bullet107 ap" "AP 107mm"}
		{"bullet107 apcr" "APCR 107mm"}
		{"bullet107 fg" "HE 107mm"}
		{"bullet152 apcr" "APCR 152mm"}
		{"bullet155 heat" "HEAT 155mm"}
		{"bullet152 heat" "HEAT 152mm"}
		{"bullet150 heat" "HEAT 150mm"}
		{"bullet122 heat" "HEAT 122mm"}
		{"bullet120 heat" "HEAT 120mm"}
		{"bullet105 heat" "HEAT 105mm"}
		{"bullet100 heat" "HEAT 100mm"}
		{"bullet90 heat" "HEAT 90mm"}
		{"bullet88 heat" "HEAT 88mm"}
		{"bullet85 heat" "HEAT 85mm"}
		{"bullet76 heat" "HEAT 76mm"}
		{"bullet75 heat" "HEAT 75mm"}
		{"bullet234" "234mm ammo"}
		{"bullet240" "240mm ammo"}
;end