		{"mp"
			{"afg"
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"0cw_mgun" "<c(c3baae)>machine gunner"}
				{"0cw_mgun2" "<c(c3baae)>machine gunner"}
				{"0cw_oficer" "<c(c3baae)>officer"}
				{"0cw_rifle" "<c(c3baae)>rifleman"}
				{"0cw_rifle2" "<c(c3baae)>assault rifleman"}
				{"0cw_engineer" "<c(c3baae)>combat engineer"}
				{"0cw_smg" "<c(c3baae)>assault SMG infantry"}
				{"0cw_smg2" "<c(c3baae)>assault SMG infantry"}
				{"0cw_sniper" "<c(c3baae)>sniper"}
				{"0cw_sniper2" "<c(c3baae)>marksman"}
				{"0cw_squadleader" "<c(c3baae)>squad leader"}
				{"0cw_squadleader2" "<c(c3baae)>assault squad leader"}
			}
			{"usa"
				{"0cw_bazooker" "<c(c3baae)>AT infantry"};cgm3
				{"0cw_bazooker2" "<c(c3baae)>AT support infantry"};support
				{"0cw_bazooker3" "<c(c3baae)>AT infantry"};m72
				{"0cw_elite" "<c(c3baae)>green beret"}
				{"0cw_elite2" "<c(c3baae)>green beret"}
				{"0cw_elite3" "<c(c3baae)>green beret"}
				{"0cw_elite4" "<c(c3baae)>ranger"}
				{"0cw_elite5" "<c(c3baae)>ranger"}
				{"0cw_elite6" "<c(c3baae)>ranger"}
				{"0cw_flamer" "<c(c3baae)>flamethrower infantry"}
				{"0cw_flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"0cw_home_guard" "<c(c3baae)>national guards"}
				{"0cw_home_guard2" "<c(c3baae)>national guards"}
				{"0cw_medic" "<c(c3baae)>medic"}
				{"0cw_mgun" "<c(c3baae)>machine gunner"};7.62X51 mgun
				{"0cw_mgun2" "<c(c3baae)>machine gunner"};5.56 mgun
				{"0cw_oficer" "<c(c3baae)>officer"}
				{"0cw_radioman" "<c(c3baae)>radio operator"}
				{"0cw_rifle" "<c(c3baae)>rifleman"}
				{"0cw_rifle2" "<c(c3baae)>assault rifleman"}
				{"0cw_engineer" "<c(c3baae)>combat engineer"}
				{"0cw_smg" "<c(c3baae)>SMG infantry"}
				{"0cw_smg2" "<c(c3baae)>assault SMG infantry"}
				{"0cw_sniper" "<c(c3baae)>sniper"}
				{"0cw_sniper2" "<c(c3baae)>marksman"}
				{"0cw_sturmovik" "<c(c3baae)>Delta"}
				{"0cw_sturmovik2" "<c(c3baae)>Delta"}
				{"0cw_sturmovik3" "<c(c3baae)>Delta"}
				{"0cw_sturmovik4" "<c(c3baae)>Delta"}
				{"0cw_sturmovik5" "<c(c3baae)>Delta"}
				{"0cw_squadleader" "<c(c3baae)>squad leader"}
				{"0cw_squadleader2" "<c(c3baae)>assault squad leader"}
				{"0cw_tankman" "<c(c3baae)>tank crew"}
				{"0cw_tankman2" "<c(c3baae)>tank commander"}
				{"0cw_vehicle_supporter" "<c(c3baae)>soldier"}

				{"1md_bazooker" "<c(c3baae)>AT infantry"};cgm3
				{"1md_bazooker2" "<c(c3baae)>AT support infantry"};support
				{"1md_bazooker3" "<c(c3baae)>AT infantry"};at4
				{"1md_elite" "<c(c3baae)>green beret"}
				{"1md_elite2" "<c(c3baae)>green beret"}
				{"1md_elite3" "<c(c3baae)>green beret"}
				{"1md_elite4" "<c(c3baae)>ranger"}
				{"1md_elite5" "<c(c3baae)>ranger"}
				{"1md_elite6" "<c(c3baae)>ranger"}
				{"1md_flamer" "<c(c3baae)>flamethrower infantry"}
				{"1md_flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"1md_home_guard" "<c(c3baae)>national guards"}
				{"1md_home_guard2" "<c(c3baae)>national guards"}
				{"1md_medic" "<c(c3baae)>medic"}
				{"1md_mgun" "<c(c3baae)>machine gunner"};7.62X51 mgun
				{"1md_mgun2" "<c(c3baae)>machine gunner"};5.56 mgun
				{"1md_oficer" "<c(c3baae)>officer"}
				{"1md_radioman" "<c(c3baae)>radio operator"}
				{"1md_rifle" "<c(c3baae)>assault rifleman"}
				{"1md_rifle2" "<c(c3baae)>assault rifleman"}
				{"1md_engineer" "<c(c3baae)>combat engineer"}
				{"1md_smg" "<c(c3baae)>assault rifleman"}
				{"1md_smg2" "<c(c3baae)>assault rifleman"}
				{"1md_sniper" "<c(c3baae)>sniper"}
				{"1md_sniper2" "<c(c3baae)>DM"}
				{"1md_sturmovik" "<c(c3baae)>Delta"}
				{"1md_sturmovik2" "<c(c3baae)>Delta"}
				{"1md_sturmovik3" "<c(c3baae)>Delta"}
				{"1md_sturmovik4" "<c(c3baae)>Delta"}
				{"1md_sturmovik5" "<c(c3baae)>Delta"}
				{"1md_squadleader" "<c(c3baae)>squad leader"}
				{"1md_squadleader2" "<c(c3baae)>assault squad leader"}
				{"1md_tankman" "<c(c3baae)>tank crew"}
				{"1md_tankman2" "<c(c3baae)>tank commander"}
				{"1md_vehicle_supporter" "<c(c3baae)>soldier"}
			}
			{"rus"
				{"0cw_bazooker" "<c(c3baae)>AT infantry"};RPG7 500mm
				{"0cw_bazooker2" "<c(c3baae)>AT support infantry"};support
				{"0cw_bazooker3" "<c(c3baae)>AT infantry"};RPG7 300mm
				{"0cw_bazooker4" "<c(c3baae)>Internal Troops AT infantry"};RPG22
				{"0cw_elite" "<c(c3baae)>VDV"}
				{"0cw_elite2" "<c(c3baae)>VDV"}
				{"0cw_elite3" "<c(c3baae)>VDV"}
				{"0cw_elite4" "<c(c3baae)>VDV"}
				{"0cw_elite5" "<c(c3baae)>VDV"}
				{"0cw_elite6" "<c(c3baae)>VDV"}
				{"0cw_flamer" "<c(c3baae)>flamethrower infantry"}
				{"0cw_flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"0cw_home_guard" "<c(c3baae)>national guards"}
				{"0cw_home_guard2" "<c(c3baae)>national guards"}
				{"0cw_medic" "<c(c3baae)>medic"}
				{"0cw_mgun" "<c(c3baae)>machine gunner"};7.62X51 mgun
				{"0cw_mgun2" "<c(c3baae)>Internal Troops machine gunner"};5.45 mgun
				{"0cw_oficer" "<c(c3baae)>officer"}
				{"0cw_radioman" "<c(c3baae)>radio operator"}
				{"0cw_rifle" "<c(c3baae)>rifleman"}
				{"0cw_rifle2" "<c(c3baae)>Internal Troops rifleman"}
				{"0cw_engineer" "<c(c3baae)>combat engineer"}
				{"0cw_smg" "<c(c3baae)>SMG infantry"}
				{"0cw_smg2" "<c(c3baae)>Internal Troops SMG infantry"}
				{"0cw_sniper" "<c(c3baae)>sniper"}
				{"0cw_sniper2" "<c(c3baae)>Internal Troops sniper"}
				{"0cw_sturmovik" "<c(c3baae)>Alpha"}
				{"0cw_sturmovik2" "<c(c3baae)>Alpha"}
				{"0cw_sturmovik3" "<c(c3baae)>Alpha"}
				{"0cw_sturmovik4" "<c(c3baae)>Alpha"}
				{"0cw_sturmovik5" "<c(c3baae)>Alpha"}
				{"0cw_squadleader" "<c(c3baae)>squad leader"}
				{"0cw_squadleader2" "<c(c3baae)>Internal Troops squad leader"}
				{"0cw_tankman" "<c(c3baae)>tank crew"}
				{"0cw_tankman2" "<c(c3baae)>tank commander"}
				{"0cw_vehicle_supporter" "<c(c3baae)>soldier"}

				{"1md_bazooker" "<c(c3baae)>AT infantry"};RPG7 500mm
				{"1md_bazooker2" "<c(c3baae)>AT support infantry"};support
				{"1md_bazooker3" "<c(c3baae)>AT infantry"};RPG7 300mm
				{"1md_bazooker4" "<c(c3baae)>AT infantry"};RPG22
				{"1md_elite" "<c(c3baae)>VDV"}
				{"1md_elite2" "<c(c3baae)>VDV"}
				{"1md_elite3" "<c(c3baae)>VDV"}
				{"1md_elite4" "<c(c3baae)>VDV"}
				{"1md_elite5" "<c(c3baae)>VDV"}
				{"1md_elite6" "<c(c3baae)>VDV"}
				{"1md_flamer" "<c(c3baae)>flamethrower infantry"}
				{"1md_flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"1md_home_guard" "<c(c3baae)>national guards"}
				{"1md_home_guard2" "<c(c3baae)>national guards"}
				{"1md_medic" "<c(c3baae)>medic"}
				{"1md_mgun" "<c(c3baae)>machine gunner"};7.62X51 mgun
				{"1md_mgun2" "<c(c3baae)>Internal Troops machine gunner"};5.45 mgun
				{"1md_oficer" "<c(c3baae)>officer"}
				{"1md_radioman" "<c(c3baae)>radio operator"}
				{"1md_rifle" "<c(c3baae)>assault rifleman"}
				{"1md_rifle2" "<c(c3baae)>Internal Troops rifleman"}
				{"1md_engineer" "<c(c3baae)>combat engineer"}
				{"1md_smg" "<c(c3baae)>assault rifleman"}
				{"1md_smg2" "<c(c3baae)>Internal Troops rifleman"}
				{"1md_sniper" "<c(c3baae)>sniper"}
				{"1md_sniper2" "<c(c3baae)>Internal Troops sniper"}
				{"1md_sturmovik" "<c(c3baae)>Alpha"}
				{"1md_sturmovik2" "<c(c3baae)>Alpha"}
				{"1md_sturmovik3" "<c(c3baae)>Alpha"}
				{"1md_sturmovik4" "<c(c3baae)>Alpha"}
				{"1md_sturmovik5" "<c(c3baae)>Alpha"}
				{"1md_squadleader" "<c(c3baae)>squad leader"}
				{"1md_squadleader2" "<c(c3baae)>Internal Troops squad leader"}
				{"1md_tankman" "<c(c3baae)>tank crew"}
				{"1md_tankman2" "<c(c3baae)>tank commander"}
				{"1md_vehicle_supporter" "<c(c3baae)>soldier"}
			}
			{"eng"
				{"0cw_sturmovik" "<c(c3baae)>SAS"}
				{"0cw_sturmovik2" "<c(c3baae)>SAS"}
				{"0cw_sturmovik3" "<c(c3baae)>SAS"}
				{"0cw_sturmovik4" "<c(c3baae)>SAS"}
				{"0cw_sturmovik5" "<c(c3baae)>SAS"}
			}
			{"kor"
				{"rifle" "<c(c3baae)>rifleman"}
				{"smg" "<c(c3baae)>SMG infantry"}
			}
			{"fra"
				{"0cw_sturmovik" "<c(c3baae)>GIGN"}
				{"0cw_sturmovik2" "<c(c3baae)>GIGN"}
				{"0cw_sturmovik3" "<c(c3baae)>GIGN"}
				{"0cw_sturmovik4" "<c(c3baae)>GIGN"}
				{"0cw_sturmovik5" "<c(c3baae)>GIGN"}

				{"1md_sturmovik" "<c(c3baae)>GIGN"}
				{"1md_sturmovik2" "<c(c3baae)>GIGN"}
				{"1md_sturmovik3" "<c(c3baae)>GIGN"}
				{"1md_sturmovik4" "<c(c3baae)>GIGN"}
				{"1md_sturmovik5" "<c(c3baae)>GIGN"}

				{"ap_miner" "<c(c3baae)>combat engineer (AP mines)"}
				{"at_miner" "<c(c3baae)>combat engineer (AT mines)"}
				{"at_rifle" "<c(c3baae)>AT-Rifle infantry"}
				{"at_rifle2" "<c(c3baae)>AT-Rifle support infantry"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"elite" "<c(c3baae)>foreign legion"}
				{"elite2" "<c(c3baae)>foreign legion"}
				{"elite3" "<c(c3baae)>foreign legion"}
				{"elite4" "<c(c3baae)>foreign legion"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"home_guard" "<c(c3baae)>resistance"}
				{"home_guard2" "<c(c3baae)>resistance"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
				{"oficer" "<c(c3baae)>officer"}
				{"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"sniper" "<c(c3baae)>sniper"}
				{"sturmovik" "<c(c3baae)>assault infantry"}
				{"sturmovik2" "<c(c3baae)>assault infantry"}
				{"sturmovik3" "<c(c3baae)>assault infantry"}
				{"sturmovik4" "<c(c3baae)>assault infantry"}
				{"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
			{"ger"
				{"mgun3" "<c(c3baae)>SS12 machine gunner"}
				{"smg3" "<c(c3baae)>SS12 SMG infantry"}
				{"rifle3" "<c(c3baae)>SS12 rifleman"}
				{"smg2" "<c(c3baae)>Waffen-SS SMG infantry"}
				{"rifle2" "<c(c3baae)>Waffen-SS rifleman"}
				{"squadleader2" "<c(c3baae)>Waffen-SS squad leader"}
			}
			{"hun"
				{"ap_miner" "<c(c3baae)>combat engineer (AP mines)"}
				{"at_miner" "<c(c3baae)>combat engineer (AT mines)"}
				{"at_rifle" "<c(c3baae)>AT-Rifle infantry"}
				{"at_rifle2" "<c(c3baae)>AT-Rifle support infantry"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"elite" "<c(c3baae)>commando"}
				{"elite2" "<c(c3baae)>commando"}
				{"elite3" "<c(c3baae)>commando"}
				{"elite4" "<c(c3baae)>commando"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"home_guard" "<c(c3baae)>conscript"}
				{"home_guard2" "<c(c3baae)>conscript"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
				{"oficer" "<c(c3baae)>officer"}
				{"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"sniper" "<c(c3baae)>sniper"}
				{"sturmovik" "<c(c3baae)>assault infantry"}
				{"sturmovik2" "<c(c3baae)>assault infantry"}
				{"sturmovik3" "<c(c3baae)>assault infantry"}
				{"sturmovik4" "<c(c3baae)>assault infantry"}
				{"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
			{"chi"
				{"0cw_narrator_chi" "<c(c3baae)>Xu Guanglin"}
				{"0cw_bazooker" "<c(c3baae)>recoilless rifle infantry"};type65
				{"0cw_bazooker2" "<c(c3baae)>AT support infantry"};support
				{"0cw_bazooker3" "<c(c3baae)>AT infantry"};rpg7
				{"0cw_bazooker4" "<c(c3baae)>AT infantry"};rpg2
				{"0cw_elite" "<c(c3baae)>airborne"}
				{"0cw_elite2" "<c(c3baae)>airborne"}
				{"0cw_elite3" "<c(c3baae)>airborne"}
				{"0cw_elite4" "<c(c3baae)>motorized infantry"}
				{"0cw_elite5" "<c(c3baae)>motorized infantry"}
				{"0cw_elite6" "<c(c3baae)>motorized infantry"}
				{"0cw_flamer" "<c(c3baae)>flamethrower infantry"}
				{"0cw_flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"0cw_forlorn_hope" "<c(c3baae)>forlorn hope"}
				{"0cw_home_guard" "<c(c3baae)>militiaman"}
				{"0cw_home_guard2" "<c(c3baae)>militiaman"}
				{"0cw_medic" "<c(c3baae)>medic"}
				{"0cw_mgun" "<c(c3baae)>machine gunner"};7.62X54 mgun
				{"0cw_mgun2" "<c(c3baae)>machine gunner"};7.62X39 mgun
				{"0cw_oficer" "<c(c3baae)>officer"}
				{"0cw_radioman" "<c(c3baae)>radio operator"}
				{"0cw_rifle" "<c(c3baae)>rifleman"}
				{"0cw_rifle2" "<c(c3baae)>dagger squad rifleman"}
				{"0cw_engineer" "<c(c3baae)>combat engineer"}
				{"0cw_saper" "<c(c3baae)>sapper"}
				{"0cw_smg" "<c(c3baae)>SMG infantry"}
				{"0cw_smg2" "<c(c3baae)>dagger squad SMG infantry"}
				{"0cw_sniper" "<c(c3baae)>sniper"}
				{"0cw_sniper2" "<c(c3baae)>marksman"}
				{"0cw_sturmovik" "<c(c3baae)>scout"}
				{"0cw_sturmovik2" "<c(c3baae)>scout"}
				{"0cw_sturmovik3" "<c(c3baae)>scout"}
				{"0cw_sturmovik4" "<c(c3baae)>scout"}
				{"0cw_sturmovik5" "<c(c3baae)>scout"}
				{"0cw_squadleader" "<c(c3baae)>squad leader"}
				{"0cw_squadleader2" "<c(c3baae)>dagger squad leader"}
				{"0cw_tankman" "<c(c3baae)>tank crew"}
				{"0cw_tankman2" "<c(c3baae)>tank commander"}
				{"0cw_vehicle_supporter" "<c(c3baae)>soldier"}

				{"narrator_chi" "<c(c3baae)>Xu Guanglin"}
				{"ap_miner" "<c(c3baae)>combat engineer (AP mines)"}
				{"at_miner" "<c(c3baae)>combat engineer (AT mines)"}
				{"at_rifle" "<c(c3baae)>AT-Rifle infantry"}
				{"at_rifle2" "<c(c3baae)>AT-Rifle support infantry"}
				{"bazooker" "<c(c3baae)>AT infantry"}
				{"bazooker2" "<c(c3baae)>AT support infantry"}
				{"elite" "<c(c3baae)>dagger platoon"}
				{"elite2" "<c(c3baae)>dagger platoon"}
				{"elite3" "<c(c3baae)>dagger platoon"}
				{"elite4" "<c(c3baae)>38th army"}
				{"elite5" "<c(c3baae)>38th army"}
				{"elite6" "<c(c3baae)>38th army"}
				{"flamer" "<c(c3baae)>flamethrower infantry"}
				{"flamer2" "<c(c3baae)>flamethrower support infantry"}
				{"forlorn_hope" "<c(c3baae)>forlorn hope"}
				{"home_guard" "<c(c3baae)>armed police force"}
				{"home_guard2" "<c(c3baae)>armed police force"}
				{"medic" "<c(c3baae)>medic"}
				{"mgun" "<c(c3baae)>machine gunner"}
				{"oficer" "<c(c3baae)>officer"}
				{"radioman" "<c(c3baae)>radio operator"}
				{"rifle" "<c(c3baae)>rifleman"}
				{"rifle2" "<c(c3baae)>assault rifleman"}
				{"saper" "<c(c3baae)>mine disposal expert"}
				{"smg" "<c(c3baae)>SMG infantry"}
				{"smg2" "<c(c3baae)>assault SMG infantry"}
				{"scout" "<c(c3baae)>scout"}
				{"sniper" "<c(c3baae)>marksman"}
				{"sturmovik" "<c(c3baae)>motorized infantry"}
				{"sturmovik2" "<c(c3baae)>motorized infantry"}
				{"sturmovik3" "<c(c3baae)>motorized infantry"}
				{"sturmovik4" "<c(c3baae)>motorized infantry"}
				{"squadleader" "<c(c3baae)>squad leader"}
				{"squadleader2" "<c(c3baae)>assault squad leader"}
				{"tankman" "<c(c3baae)>tank crew"}
				{"tankman2" "<c(c3baae)>tank commander"}
				{"vehicle_supporter" "<c(c3baae)>soldier"}
			}
		}