;{tags
	{"special"
		{"rhmb_wt150" "<c(c3baae)>tank destroyer</c>"}
		{"rhmb_wt" "<c(c3baae)>tank destroyer</c>"}
		{"hetzer2" "<c(c3baae)>tank destroyer</c>"}
		{"hetzer_hun" "<c(c3baae)>tank destroyer</c>"}
		{"kugelblitz_flak58" "<c(c3baae)>AA tank</c>"}
		{"kugelblitz_MK103" "<c(c3baae)>AA tank</c>"}
		{"kugelblitz_MK103_MG151" "<c(c3baae)>AA tank</c>"}
		{"obj704" "<c(c3baae)>heavy tank destroyer</c>"}
		{"obj704_0" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"isu130" "<c(c3baae)>heavy tank destroyer</c>"}
		{"isu122_chi" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"pz1_75mm" "<c(c3baae)>light tank destroyer</c>"}
		{"panzerjager" "<c(c3baae)>light tank destroyer</c>"}
		{"280br5" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"foch155" "<c(c3baae)>heavy tank destroyer</c>"}
		{"ca10_eng" "<c(c3baae)>engineer truck</c>"}
		{"ca10_inf" "<c(c3baae)>supply truck</c>"}
		{"ca10_art" "<c(c3baae)>supply truck</c>"}
		{"renault_eng" "<c(c3baae)>engineer truck</c>"}
		{"botond_inf" "<c(c3baae)>supply truck</c>"}
		{"botond_art" "<c(c3baae)>supply truck</c>"}
		{"renault_inf" "<c(c3baae)>supply truck</c>"}
		{"renault_art" "<c(c3baae)>supply truck</c>"}
		{"renault_aa" "<c(c3baae)>AA vehicle</c>"}
		{"type63_selfaa" "<c(c3baae)>AA tank</c>"}
		{"lvt4_76" "<c(c3baae)>tank destroyer</c>"}
		{"lvt4_57" "<c(c3baae)>tank destroyer</c>"}
		{"su76_chi" "<c(c3baae)>self-propelled howitzer</c>"}
		{"isu152_chi" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"su100_chi" "<c(c3baae)>heavy tank destroyer</c>"}
		{"zpu_4" "<c(c3baae)>AA mgun</c>"}
		{"120_mm_mortar_pm_38" "<c(c3baae)>heavy mortar</c>"}
		{"120_mm_mortar_type55" "<c(c3baae)>heavy mortar</c>"}
		{"nj230_type63" "<c(c3baae)>rocket artillery</c>"}
		{"type63_type70_rocket" "<c(c3baae)>rocket artillery</c>"}
		{"type63_rocket" "<c(c3baae)>rocket artillery</c>"}
		{"bm31" "<c(c3baae)>rocket artillery</c>"}
		{"t92" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"0bj_268" "<c(c3baae)>heavy tank destroyer</c>"}
		{"conqueror_gun" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"su122a" "<c(c3baae)>self-propelled howitzer</c>"}
		{"gw_pz6" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"g_e" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"jagdpz_e100a" "<c(c3baae)>supper heavy tank destroyer</c>"}
		{"jagdtiger_128l66" "<c(c3baae)>heavy tank destroyer</c>"}
		{"elefant_128" "<c(c3baae)>heavy tank destroyer</c>"}
		{"mkVibAA" "<c(c3baae)>AA tank</c>"}
		{"cruisermk3" "<c(c3baae)>cruiser tank</c>"}
		{"cruisermk1" "<c(c3baae)>cruiser tank</c>"}
		{"StuH42e" "<c(c3baae)>assault gun</c>"}
		{"stug4g" "<c(c3baae)>assault gun</c>"}
		{"StuG3Ge" "<c(c3baae)>assault gun</c>"}
		{"stug3f" "<c(c3baae)>assault gun</c>"}
		{"stug3b" "<c(c3baae)>assault gun</c>"}
		{"stug" "<c(c3baae)>assault gun</c>"}
		{"brummbar" "<c(c3baae)>assault gun</c>"}
		{"sig33b" "<c(c3baae)>assault gun</c>"}
		{"su101" "<c(c3baae)>heavy tank destroyer</c>"}
		{"su_100m1" "<c(c3baae)>heavy tank destroyer</c>"}
		{"tortez" "<c(c3baae)>supper heavy tank destroyer</c>"}
		{"fv215b_183" "<c(c3baae)>heavy tank destroyer</c>"}
		{"t28prot" "<c(c3baae)>supper heavy tank destroyer</c>"}
		{"t95" "<c(c3baae)>supper heavy tank destroyer</c>"}
		{"t28" "<c(c3baae)>supper heavy tank destroyer</c>"}
		{"dickermax" "<c(c3baae)>heavy tank destroyer</c>"}
		{"jpz4l48" "<c(c3baae)>heavy tank destroyer</c>"}
		{"jpz4l70a" "<c(c3baae)>heavy tank destroyer</c>"}
		{"t48" "<c(c3baae)>light tank destroyer</c>"}
		{"pz4_wt" "<c(c3baae)>tank destroyer</c>"}
		{"marder135" "<c(c3baae)>tank destroyer</c>"}
		{"marder139" "<c(c3baae)>tank destroyer</c>"}
		{"marder_3m" "<c(c3baae)>tank destroyer</c>"}
		{"grille" "<c(c3baae)>self-propelled howitzer</c>"}
		{"sturmpz1" "<c(c3baae)>self-propelled howitzer</c>"}
		{"bison2" "<c(c3baae)>self-propelled howitzer</c>"}
		{"su14" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"g_e" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"su152" "<c(c3baae)>heavy self-propelled howitzer</c>"}
		{"su5" "<c(c3baae)>self-propelled howitzer</c>"}
		{"churchill_kangaroo" "<c(c3baae)>kangaroo</c>"}
		{"karlthor" "<c(c3baae)>super heavy self-propelled howitzer</c>"}
		{"kv8_41" "<c(c3baae)>flame tank</c>"}
		{"pz3_m_flamer" "<c(c3baae)>flame tank</c>"}
		{"ot34_2" "<c(c3baae)>flame tank</c>"}
		{"hetzer_fl" "<c(c3baae)>flame tank</c>"}
	}
;}
