
;new
		{"helmet1_hun" "Helmet"}
		{"helmet2_hun" "Helmet"}
		{"fieldcap1_hun" "Cap"}
		{"fieldcap2_hun" "Cap"}
		{"fieldcap3_hun" "Cap"}
		{"radiocap_hun" "Radio cap"}
		{"tankhelmet2_hun" "Tank Helmet"}
		{"hungarian_36m" "AP grenade kezigranat 36m"}	
		{"hungarian_42m" "AP grenade kezigranat 42m"}
		{"kasapanos" "AT grenade kasapanos"}
		{"helmet1_fr" "Helmet"}
		{"fr_paradropammo" "Signal - ammo paradrop"}
		{"fr_paradropammo_heavy" "Signal - heavy ammo paradrop"}
		{"n73at" "AT granade N73"}
		{"beret_fra" "Beret"}
		{"beret_fra1" "Beret"}
		{"cap_fra" "Cap"}
		{"cap_fra1" "Cap"}
		{"cap_fra2" "Cap"}
		{"fra_casco_M32"  "Helmet"}
		{"fra_kepi" "Kepi"}
		{"fra_kepi_1" "Kepi"}
		{"fra_tankcap" "Tank Helmet"}
		{"helmet_fra" "Helmet"}
		{"helmet_fra1" "Helmet"}
		{"helmet_fra2" "Helmet"}
		{"legion_cap" "Cap"}
		{"legion_cap1" "Cap"}
;end