
;new
		{"is6_1" "IS-6(122mm M-62)"}
		{"is6" "IS-6(122mm D-30)"}
		{"m42" "45mm M1942"}
		{"155mm_m1917a4" "155mm M1917"}
		{"flak41" "Flak18/36/37"}
		{"rhmb_wt150" "Rhm.-Borsig Waffentrager(150mm)"}
		{"rhmb_wt" "Rhm.-Borsig Waffentrager(128mm)"}
		{"hetzer2" "Hetzer"}
		{"kugelblitz_MK103_MG151" "Kugelblitz(2cm MK151)"}
		{"kugelblitz_MK103" "Kugelblitz(3cm MK103)"}
		{"kugelblitz_flak58" "Kugelblitz(5cm Flak41)"}
		{"staghound" "Staghound"}
		{"staghound_mk1e" "Staghound"}
		{"wasp" "Wasp"}
		{"po2" "Po-2"}
		{"i-16" "I-16"}
		{"hurricane23" "Hurricane"}
		{"isu130" "ISU-130"}
		{"obj704_0" "Object704(ML-20)"}
		{"obj704" "Object704(BL-10)"}
		{"sdkfz301wanze" "SdKfz 301"}
		{"np_ho_ki" "Type 1 Ho-Ki"}
		{"quad" "Ford F-GT"}
		{"np_su12" "Su-12"}
		{"m6a2e1" "M6A2E1"}
		{"m4a1_revalorise" "M4A1 Revalorise"}
		{"m46_1" "M46(165mm AVRE)"}
		{"type_60_tractor" "Type60"}
		{"ba20" "BA-20"}
		{"t-28" "T-28"}
		{"t-28_e" "T-28E"}
		{"is3_2" "IS-3(122mm BL9)"}
		{"is3_1" "IS-3(100mm D10T)"}
		{"is3_0" "IS-3"}
		{"t-80_20k" "T-80"}
		{"t-80_vt43" "T-80(VT-42)"}
		{"t-80_sha37" "T-80(Sha-37)"}
		{"vk4503" "VK 45.03"}
		{"panzerjager" "PanzerJager I"}
		{"isu122_chi" "Su-122"}
		{"vk1602" "VK 16.02"}
		{"a19" "A19"}
		{"e-50" "E50"}
		{"type58AA" "Type58 AA"}
		{"o-i" "O-I"}
		{"m46" "M46"}
		{"type89" "Type 89"}
		{"t110e5" "T110E5"}
		{"sdkfz231" "SdKfz 231"}
		{"sdkfz8_flak" "88mm Flak18 SfI"}
		{"pz1_75mm" "PanzerJager I(75mm Pak40)"}
		{"pz5d" "PzKpfw V Ausf.D Panther"}
		{"is5" "IS-5"}
		{"obj260" "Object260"}
		{"f4f" "F-4F"}
		{"f4" "F-4"}
		{"a-10" "A-10"}
		{"hummer" "Hummer"}
		{"m113" "M113"}
		{"m1a1" "M1A1"}
		{"YW531A" "YW531"}
		{"type63" "Type63"}
		{"m113" "M113"}
		{"bradley" "M2/3 Bradley"}
		{"t64b" "T-64B"}
		{"gaz_vodnik" "GAZ Vodnik"}
		{"btr80" "BTR-80"}
		{"btr60" "BTR-60"}
		{"dingo" "Dingo"}
		{"man" "Man"}
		{"man_ammo" "Man"}
		{"man_eng" "Dingo"}
		{"marder" "Marder1A3"}
		{"tpz1" "TPz-1 Fox"}
		{"tpz1a4" "TPz-1A4 Fox"}
		{"mi28" "Mi-28"}
		{"asu85" "ASU-85"}
		{"mig17" "Mig-17"}
		{"mig17_bomber" "Mig-17"}
		{"china59d" "Type59D"}
		{"jaguar" "Type59 Jaguar"}
		{"ztz85iii" "Type85 III"}
		{"type99" "Type99 II"}
		{"china98" "Type99 (9910)"}
		{"t62a" "T-62"}
		{"challengerii" "Challenger II"}
		{"leopard2a7" "Leopard 2A7"}
		{"leopard2a6" "Leopard 2A6"}
		{"m1a2" "M1A2"}
		{"rus_t-72a" "T-72A"}
		{"t-62" "T-62"}
		{"m60" "M60"}
		{"m47" "M47"}
		{"leopard1" "Leopard 1"}
		{"object279" "Object 279"}
		{"m48a3" "M48A3"}
		{"t49" "T49"}
		{"m41" "M41"}
		{"280br5" "280mm BR-5"}
		{"np_ml20" "152mm ML-20"}
		{"gaz-aaa_4m" "Gaz AA"}
		{"np_lrdg_20mm" "Chevrolet 30 cwt AA"}
		{"np_lrdg_37mm" "Chevrolet 30 cwt AT"}
		{"np_willys50" "Willys MB .50 HMG"}
		{"np_willysat" "Willys AT"}
		{"np_willysmb" "Willys MB"}
		{"np_willysmb_en" "Willys MB"}
		{"type95" "Type95 Jeep"}
		{"schwimmwagen" "VW166 Schwimmwagen"}
		{"hotchkiss_stan" "Heavy MG"}
		{"wz111_5" "WZ-111 model5"}
		{"wz111_4" "WZ-111 model4"}
		{"wz111_1" "WZ-111 model0"}
		{"wz111" "WZ-111 model1"}
                {"foch155" "AMX 50 Foch (155)"}
                {"hotchkiss_mgun" "Hotchkiss M.1914"}
                {"75mm_vickers" "75mm DCA Mle 32"}
                {"mle27" "81mm Brandt Mle 27"}
                {"r35" "Renault R-35"}
		{"r39" "Renault R-39"}
                {"h39" "Hotchkiss H-39"}
                {"ft17" "Renault FT-17"}
                {"bs-75" "Renault FT-75 BS"}
                {"amr35-13mm" "AMR 35 ZT 1"}
                {"amr35-25m" "AMR 35 ZT 2"}
		{"13mm_hotchkiss" "13,2mm CA Mle.30"}
                {"25mm_sa34" "25mm SA-34 Mle 34"}
                {"37mm_shneider" "37mm DCA Mle 30"}
                {"47mm_sa37" "47mm SA-37 Mle 37"}
                {"75mm_1897" "75mm Canon M 1897"}
                {"105mm_m1913" "Canon 105 M.1913 S"}
		{"155mm_mle1917" "155mm Canon 1917 Shneider"}
                {"laffly_s15_toe" "Laffly S15 TOE"}
                {"panhard" "AMD-35 Panhard 178"}
                {"lorraine" "TRC Lorraine 38L VBCP"}
                {"lorrai_37_47" "TRC Lorraine 37L"}
                {"lorrai" "Lorraine 37L"}
                {"b1bis" "Char B1-bis"}
                {"b1b_fra" "Char B1-bis"}
                {"b1b_flamm" "Char B1flame"}
                {"chardebat_d2" "Renault D2 M39"}
                {"s35" "Somua S-35"}
                {"renoult" "Renault AHN"}
                {"renault_inf" "Renault AHS"}
                {"renault_art" "Renault AGK"}
                {"renault_eng" "Renault AGE"}
                {"renault_t" "Renault 2T"}
                {"renault_aa" "Renault AA"}
                {"gnome" "Gnome et Rhone ’¿II"}
                {"cj750" "Chang Jiang 750"}
		{"bat25t" "Bat.-Chatillon 25 t"}
		{"elc_amx_40" "AMX 40"}
		{"elc_amx" "ELC AMX"}
		{"amx40" "AMX 40"}
		{"amx-13-90" "AMX 13 90"}
		{"amx12t" "AMX 12 t"}
		{"arl44" "ARL 44"}
		{"amx50-100" "AMX 50 100"}
		{"AMX_50b" "AMX 50 B"}
		{"is2u_2" "110(100mm)"}
		{"is2u_1" "110(122mm)"}
		{"110" "110"}
		{"is2u" "IS-2U"}
		{"type99" "Type 99"}
		{"62tank" "Type 62"}
		{"59-122tank" "Type 59(122mm)"}
		{"59tank" "Type 59"}
		{"stug3g_hun" "Stug III"}
		{"pz5a_hun" "PzKpfw V Panther"}
		{"pz4g_hun" "PzKpfw IV"}
		{"pz3_hun" "PzKpfw III"}
		{"hetzer_hun" "Hetzer"}
		{"pz6e_hun" "PzKpfw VI Tiger"}
		{"btr40_type58" "BTR-40 AA"}
		{"zsl56" "BTR-152"}
		{"btr152" "BTR-152"}
		{"type63_selfaa" "Type63 SPAA"}
		{"Chi-ArmoredCar" "Type36(37mm)"}
		{"Chi-ArmoredCar_1" "Type36(Mgun)"}
		{"ha-go_chi" "Type 95"}
		{"ba64_chi" "BA-64"}
		{"t34_3_chi" "T-34/85"}
		{"t34_2_chi" "T-34/76"}
		{"su100_chi" "Su-100"}
		{"su76_chi" "Su-76"}
		{"isu152_chi" "Su-152"}
		{"is122_chi" "IS-2"}
		{"is2_chi" "IS-2"}
		{"chi-ha_chi" "Type 97"}
		{"lvt4_57" "Type55(57mm)-LVT4"}
		{"lvt4_76" "Type54(76mm)-LVT4"}
		{"pz6bh_chi" "Type 88"}
		{"type56_cannon" "Type56 85mm cannon"}
		{"120_mm_mortar_type55" "Type55 120mm mortar"}
		{"120_mm_mortar_pm_38" "M1938 120mm mortar"}
		{"type63_rocket" "Type63 107mm MRL"}
		{"bm31" "BM-31 310mm SPMRL"}
		{"nj230_type63" "Type63 130mm SPMRL"}
		{"type63_type70_rocket" "Type70 130mm SPMRL"}
		{"zpu_4" "Type56 AA"}
		{"113" "113"}
		{"ca10_ht" "Jie Fang Tractor"}
		{"type53" "Type 53 mortar"}
		{"m3a1_white" "M3A1"}
		{"m3a1_white_trans" "M3A1"}
		{"m3a1_white_scout" "M3A1"}
		{"m3a1_dpm_scout" "M3A1"}
		{"type59_16" "59-16"}
		{"type59_16_57" "59-16"}
		{"t34-1" "T-34-1(100mm)"}
		{"t34-1_0" "T-34-1(85mm)"}
		{"dshk_stan_fix" "Heavy MG"}
		{"dshk_wheeled" "Heavy MG"}
		{"gebauer_stan" "Heavy MG"}
		{"mg131_stan" "Heavy MG"}
		{"40mm_40m"  "40mm 40m"}
		{"pak97_38" "75mm Pak 97/38"}
		{"ca10_eng" "Jie Fang CA10"}
		{"ca10_art" "Jie Fang CA10"}
		{"ca10_inf" "Jie Fang CA10"}
		{"ca10" "Jie Fang CA10"}
		{"botond_eng" "38/42M Botond B"}
		{"botond_art" "38/42M Botond B"}
		{"botond_inf" "38/42M Botond B"}
		{"botond" "38/42M Botond B"}
		{"csaba40m" "40M Csaba"}
		{"csaba39m" "39M Csaba"}
		{"morris_cs8" "Morris CS8"}
		{"zrinyi2" "Zrinyi II 43M"}
		{"zrinyi1" "Zrinyi I 43M"}
		{"tas_44m" "Tas 44M"}
		{"tas_44td" "Tas 44M TD"}
		{"nimrod" "40M Nimrod"}
		{"turan3" "Turan III"}
		{"turan2" "Turan II"}
		{"turan1" "Turan I"}
		{"toldi2" "Toldi II"}
		{"toldi1" "Toldi I"}
		{"st_b1" "STB-1"}
		{"churchill_ix" "Churchill Mk.IX"}
		{"churchill_i" "Churchill Mk.I"}
		{"centurion" "Centurion MK.I"}
		{"mkvii" "Centurion MK.VII"}
		{"fv215b" "FV215b"}
		{"charioteer" "Charioteer"}
		{"t92" "T92"}
		{"jagdpanzer_iv_75l48" "Jagdpanzer IV(75mm L/48)"}
		{"0bj_268" "Object 268"}
		{"conqueror_gun" "Conqueror Gun Carriage"}
		{"pz4_st" "Pz.Kpfw. IV Schmalturm"}
		{"gw_pz6" "G.W.Tiger"}
		{"t-80" "T-80"}
		{"su122a" "Su-122A"}
		{"m6_m3" "M6(90mm M3)"}
		{"m6_m7" "M6(76mm M7)"}
		{"t14" "T-14"}
		{"kv-4-zis24_stukhov_turret" "KV-4"}
		{"vk3001d" "VK3001(D)"}
		{"vk3601h" "VK3601(H)"}
		{"elefant_128" "Elephant(128mm Pak44)"}
		{"jagdtiger_128l66" "JagdTiger(128mm L/66)"}
		{"jagdpz_e100a" "Jagdpanzer E100"}
		{"pz6b_105l68" "PzKpfw VI Kingtiger(1945)"}
		{"sws" "sWS"}
		{"sws_flak" "37mm Flak43 auf sWS"}
		{"sdkfz7_1" "Sd.kfz.7/1"}
		{"sdkfz7_flak18" "88mm Flak18 SfI"}
		{"76mm_obr1927" "76mm M1927"}
		{"75mm_shneider" "75mm Shneider1897"}
		{"75mm_leig18" "75mm le.IG18"}
		{"15_cm_sig33" "150mm sIG33"}
		{"lowe" "Lowe"}
		{"g_e" "G.W.E 100"}
		{"kv13_85" "KV-13(85mm ZIS53)"}
		{"kv13" "KV-13"}
		{"is85" "IS-1"}
		{"su_100m1" "Su-100M1"}
		{"pz4_wt" "IV WT"}
		{"pz3_4" "PzKpfw III-IV"}
		{"su101" "Su-101"}
		{"t44_2" "T-44(100)"}
		{"pz2j" "PzKpfw II Ausf.J"}
		{"t28prot" "T28(prototype)"}
		{"tog2" "TOG II"}
		{"tiger_p" "PzKpfw VI Tiger(P)"}
		{"kv4" "KV-4"}
		{"fv215b_183" "FV215b(183)"}
		{"t57ht" "T57"}
		{"m103" "M103"}
		{"m26_ha" "M26 Pershing(Heavy Armor type)"}
		{"m4a1_75" "M4A1 Sherman"}
		{"m4a1_76w" "M4A1(76) Sherman"}
		{"hetzer_fl" "Hetzer FL"}
		{"karlthor" "Karlthor"}
		{"matildamk1" "Matilda Mk.I"}
		{"marder135" "Marder I Sdkfz135"}
		{"marder139" "Marder III Sdkfz139"}
		{"marder_3m" "Marder III Sdkfz138 Ausf M"}
		{"grille" "Sdkfz138/1 Grille"}
		{"mkVibAA" "Vickers MK.VI AA"}
		{"mkVIB" "Vickers MK.VI"}
		{"m3stuartUS" "M3A1 Stuart"}
		{"m3stuartUK" "M3A1 Stuart"}
		{"m3a1" "M3A1 Stuart"}
		{"cruisermk3" "MK III"}
		{"cruisermk1" "MK I"}
		{"StuH42e" "Stuh 42"}
		{"stug4g" "Stug IV"}
		{"StuG3Ge" "Stug III G"}
		{"stug3f" "Stug III F/8"}
		{"stug3b" "Stug III B"}
		{"stug" "Stug III C/D"}
		{"m4_pershing" "M4 Pershing"}
		{"dickermax" "Dickermax"}
		{"conqueror" "Conqueror"}
		{"churchill_kangaroo" "Churchill Kangaroo"}
		{"pz4d" "PzKpfw IV Ausf.D"}
		{"pz4e" "PzKpfw IV Ausf.E"}
		{"pz4f" "PzKpfw IV Ausf.F2"}
		{"pz5a" "PzKpfw V Ausf.A Panther"}
		{"pz5g_late" "PzKpfw V Ausf.G Panther"}
		{"pz5f" "PzKpfw V Ausf.F Panther"}
		{"pz5g_75l100" "PzKpfw V Ausf.G Panther(75mm L/100)"}
		{"pz5f_75l100" "PzKpfw V Ausf.F Panther(75mm L/100)"}
		{"panther_ii" "PzKpfw V Panther II"}
		{"panther_ii_75mm" "PzKpfw V Panther II(75mm L/100)"}
		{"panther_ii_88mm" "PzKpfw V Panther II(88mm L/71)"}
		{"panther_ii_105mm" "PzKpfw V Panther II(105mm L/28)"}
		{"bt7_35" "BT-7 1935"}
		{"bt7_35k" "BT-7 1935"}
		{"bt7_37_0" "BT-7 1937"}
		{"bt7_37_1" "BT-7 1937"}
		{"t-26_1933" "T-26 1933"}
		{"sig33b" "StuIG 33B"}
		{"jpz4l48" "Jagdpanzer IV"}
		{"jpz4l70a" "Jagdpanzer IV(A)"}
		{"jagdpanzer_iv" "Jagdpanzer IV(V)"}
		{"brummbar" "Brummbar"}
		{"sturmpz1" "Bison I"}
		{"bison2" "Bison II"}
		{"sdkfz251_17" "SdKfz 251/17"}
		{"sdkfz251_9" "SdKfz 251/9"}
		{"sdkfz251_10" "SdKfz 251/10"}
		{"sdkfz251_1w" "Wurfrahmen 40"}
		{"sdkfz251" "SdKfz 251"}
		{"sdkfz234_1" "SdKfz 234/1"}
		{"sdkfz234_3" "SdKfz 234/3"}
		{"sdkfz234_4" "SdKfz 234/4"}
		{"t48" "T48"}
		{"mk_9" "Mk.X Valentine"}
		{"voroshilovets" "Voroshilovets"}
		{"m4hst" "M4 High Speed Tractor"}
		{"sdkfz8" "SdKfz 8"}
		{"tortez" "Tortez"}
		{"m48a1" "M48"}
		{"t_54" "T-54"}
		{"maus" "Maus"}
		{"t95" "T95"}
		{"t28" "T28"}
		{"t44" "T-44"}
		{"t44_122" "T-44(122)"}
		{"t34_3_ha" "T-34/85(Heavy Armor type)"}
		{"m4a3_76" "M4A3(76) Sherman"}
		{"37mm_flak36" "FlaK 36"}
		{"52k" "52K"}
		{"155mm_longtom" "M1 longtom"}
		{"pak36r" "PaK 36(r)"}
		{"pak44" "PaK 44"}
		{"churchill_mk_v_cs" "Mk.V Churchill CS"}
		{"churchill_mk_vii_77hv" "Mk.VII Churchill(77mm HV)"}
		{"churchill_mk_ix" "Mk.IX Churchill LT"}
		{"e50_ausf_m" "E50M"}
		{"e75" "E75"}
		{"e100" "E100"}
		{"e-100" "E100(128mm KwK44)"}
		{"e-100_150" "E100(150mm KwK44)"}
		{"sdkfz182b" "PzKpfw VI Kingtiger(B)"}
		{"sdkfz182h" "PzKpfw VI Kingtiger(H)"}
		{"vk4502p_b" "VK4502(P)"}
		{"pz3e" "PzKpfw III Ausf.E"}
		{"pz3l" "PzKpfw III Ausf.L"}
		{"pz3_m_flamer" "PzKpfw III Ausf.FL"}
		{"pz2c" "PzKpfw II Ausf.C"}
		{"pz2fa" "PzKpfw II Ausf.F"}
		{"pz35t" "35(t)"}
		{"pz38t" "38(t)"}
		{"t-38" "T-38"}
		{"t-40" "T-40"}
		{"t40-bm8" "T-40-BM8"}
		{"ot34_2" "OT-34"}
		{"is3_m" "IS-3"}
		{"is-4m" "IS-4M"}
		{"is4" "IS-4"}
		{"is4_100" "IS-4(100mm S-34)"}
		{"is4_m62" "IS-4(122mm M-62T)"}
		{"is7" "IS-7"}
		{"is-7" "IS-7"}
		{"t10m" "IS-8"}
		{"kv-220" "KV-220"}
		{"kv1c" "KV-1C"}
		{"kv1_57gun" "KV-1(57mm ZIS4)"}
		{"kv1c_57gun" "KV-1C(57mm ZIS4)"}
		{"kv1_75l43gun" "KV-1(75mm L/43)"}
		{"kv1c_75l43gun" "KV-1C(75mm L/43)"}
		{"kv8_41" "KV-8"}
		{"kv1s" "KV-1S"}
		{"kv1_40" "KV-1 1940"}
		{"kv1_41" "KV-1 1941"}
		{"kv3" "KV-3"}
		{"kv5" "KV-5"}
		{"pz6h" "PzKpfw VI Tiger"}
		{"pz6e_88l71gun" "PzKpfw VI Tiger(88mm Kwk43)"}
		{"su14" "Su-14"}
		{"su152" "Su-152"}
		{"is122" "IS-2"}
		{"su5" "Su-5"}
		{"challenger" "A30 Challenger Mk.VIII"}
		{"cromwell_mk_vii_57gun" "Mk.VII Cromwell(QF 6)"}
;end