
;new
		{"155mm_m1" "155mm M1 longtom"}
		{"85mm_52k" "85mm 52K"}
		{"76mm_pak36" "76mm PaK36(r)"}
		{"47mm_1938" "47mm Type1938"}
		{"105mm_t5e2" "105mm T5E3"}
		{"100mm_D10TG" "100mm D10T"}
		{"75mm_kwk44" "75mm KwK44"}
		{"105mm_t5e1" "105mm T5E1"}
		{"120mm_t53" "120mm T53"}
		{"128mm_kwk44" "128mm KwK44"}
		{"20mm_solothurn" "20mm Solothurn"}
		{"20mm_s18_100" "20mm Solothurn"}
		{"40mm_42M" "40mm 42M"}
		{"40mm_42M_pak" "40mm 42M"}
		{"40mm_bofors_36m" "40mm Bofors 36m"}
		{"75mm_41m" "75mm 41M"}
		{"75mm_43m" "75mm 43M"}
		{"75mm_pak97_38" "75mm Pak 97/38"}
		{"105mm_40_43m" "105mm 40/43M"}
		{"105mm_L13S" "105mm L13S"}
		{"155mm_lt" "155mm LT"}
		{"schwarzlose" "8mm Schwarzlose"}
		{"gebauer" "34/40M Gebauer"}
		{"danuvia_39m" "Danuvia 39M"}
		{"danuvia_43m" "Danuvia 43M"}
		{"frommer_37m" "FEG 37M"}
		{"feg_35m" " FEG 35M"}
		{"feg_43m" " FEG 43M"}
		{"mannlicher_m1895" "Steyr Mannlicher M1895"}
		{"mannlicher_m1895c" "Steyr Mannlicher M1895"}
		{"solothurn_31m" "Solothurn 31M"}
		{"mg13" "MG 13"}
		{"zh-29" "ZH-29"}
		{"zb24_s" "ZB 24/s"}
		{"ppd40" "PPD 40"}
		{"solothurn" "Solothurn S/100"}
		{"mg131" "MG 131"}
		{"13mm_hotchkiss" "13.2 mm Hotchkiss"}
		{"13mm_hotchkiss_x2" "13.2 mm Hotchkiss"}
		{"reibel" "Mitrailleuse mle 1931"}
		{"fm_24-29" "Châtellerault modèle 1929"}
		{"modele_1935" "MAS mle 1935 S"}
		{"berthier_m1916" "Berthier mle 1907 / 16"}
		{"lebel_m1886" "Lebel mle 1886 / 93"}
		{"lebel_m1886_scoped" "Lebel mle 1886 / 93 Scoped"}
		{"mas36" "MAS mle 36"}
		{"mas38" "MAS mle 1938"}
		{"hotchkiss" "Hotchkiss M.1914"}
		{"hotchkiss_13" "Hotchkiss 13.2mm HMG"}
		{"hotchkiss_132" "Hotchkiss 13.2mmX2 HMG"}
		{"hotchkiss1914" "Hotchkiss M.1914"}
		{"7,5mm_shatelro" "MAC mle.31"}
		{"mas36_grenade" "MAS mle 36 with Grenade launcher"}
;end